<?php

namespace ContainerTzHUMo0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HxQe7M6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hxQe7M6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hxQe7M6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'developerRepository' => ['privates', 'App\\Repository\\DeveloperRepository', 'getDeveloperRepositoryService', true],
            'tasksRepository' => ['privates', 'App\\Repository\\TasksRepository', 'getTasksRepositoryService', true],
        ], [
            'developerRepository' => 'App\\Repository\\DeveloperRepository',
            'tasksRepository' => 'App\\Repository\\TasksRepository',
        ]);
    }
}
