<?php

namespace ContainerTzHUMo0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMockyCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\MockyCommand' shared autowired service.
     *
     * @return \App\Command\MockyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/MockyCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Service/RequestService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/LogService.php';
        include_once \dirname(__DIR__, 4).'/src/Factory/ProviderFactory.php';
        include_once \dirname(__DIR__, 4).'/src/Service/ToDoListService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/AssignmentService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        $container->privates['App\\Command\\MockyCommand'] = $instance = new \App\Command\MockyCommand(new \App\Service\RequestService($a, ($container->privates['parameter_bag'] ?? ($container->privates['parameter_bag'] = new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container))), new \App\Service\LogService($a)), new \App\Factory\ProviderFactory(), $a, new \App\Service\ToDoListService($a), new \App\Service\AssignmentService($a));

        $instance->setName('mocky:to-do-list');

        return $instance;
    }
}
