<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVzznQdf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVzznQdf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVzznQdf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVzznQdf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVzznQdf\App_KernelDevDebugContainer([
    'container.build_hash' => 'VzznQdf',
    'container.build_id' => 'f4028041',
    'container.build_time' => 1653259226,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVzznQdf');
